apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  hostname: mysql01
  subdomain: mysqlsvc
  containers:
    - name: mysql
      image: mysql/mysql-server:5.7
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "250m"
          memory: "512Mi"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: r00tme
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  nodeSelector:
    test: worker-node02
  volumes:
    - name: mysql-data
      hostPath:
        path: /var/lib/mysql
